spring:
  datasource:
    url: jdbc:mariadb://mysql.localhost:3306/db_activiti?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: hocgin
    druid:
      validation-query: select '1'
logging:
  level:
    in.hocg: debug
    org.activiti: debug