spring:
  profiles:
    active: default
  application:
    name: rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    cache:
      channel:
        size: 40
  cloud:
    stream:
      bindings:
        # ---- 定义输出 ----
        MQ_PACKAGE_INPUT:
          # 绑定消息交换机(Exchange)
          destination: ${spring.profiles.active}.mq.package
          group: ${spring.application.name}
          content: text/plain
        # ---- 定义输入 ----
        MQ_PACKAGE_OUTPUT:
          # 绑定消息交换机(Exchange)
          destination: ${spring.profiles.active}.mq.package
          group: ${spring.application.name}
logging:
  level:
    in.hocg: debug