version: "2"
services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.0.1
    container_name: xxl-job-admin
    depends_on:
      - xxl-job-admin-db
    ports:
      - "8020:8080"
    links:
      - xxl-job-admin-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://xxl-job-admin-db:3306/xxl-job?Unicode=true&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ''

  xxl-job-admin-db:
    image: mysql:5.7
    container_name: xxl-job-admin-db
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    depends_on:
      - xxl-job-admin-dbdata
    ports:
      - "13307:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    volumes_from:
      - xxl-job-admin-dbdata

  xxl-job-admin-dbdata:
    image: alpine:latest
    container_name: xxl-job-admin-dbdata
    volumes:
      - /var/lib/mysql